//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_PartyService
    {
        public string Id { get; set; }
        public string PartyId { get; set; }
        public string ServiceUnitId { get; set; }
    
        public virtual Core_CnsServiceUnit Core_CnsServiceUnit { get; set; }
        public virtual Core_PartyMaster Core_PartyMaster { get; set; }
        public virtual Core_PrvServiceUnit Core_PrvServiceUnit { get; set; }
    }
}
