//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_CosumerServices
    {
        public int Id { get; set; }
        public Nullable<int> ConsumerId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Core_Consumers Core_Consumers { get; set; }
        public virtual Core_ServiceCatalog Core_ServiceCatalog { get; set; }
    }
}
