//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_PartyTypes
    {
        public int Id { get; set; }
        public string PartyType { get; set; }
        public string Value { get; set; }
    }
}
