//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Apointments
    {
        public int Id { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> CosumerId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Core_Consumers Core_Consumers { get; set; }
        public virtual Core_Providers Core_Providers { get; set; }
        public virtual Core_ServiceCatalog Core_ServiceCatalog { get; set; }
    }
}
