//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Providers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Core_Providers()
        {
            this.Core_Apointments = new HashSet<Core_Apointments>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProviderType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string PrimaryUsreId { get; set; }
        public string SecondaryUsreId { get; set; }
        public string Name { get; set; }
        public string Licence { get; set; }
        public string ServiceCapacity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_Apointments> Core_Apointments { get; set; }
    }
}
