//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_CnsServiceUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Core_CnsServiceUnit()
        {
            this.Core_PartyService = new HashSet<Core_PartyService>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string PrimaryUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Core_PartyService> Core_PartyService { get; set; }
    }
}
