//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Core_Address> Core_Address { get; set; }
        public virtual DbSet<Core_Apointments> Core_Apointments { get; set; }
        public virtual DbSet<Core_Consumers> Core_Consumers { get; set; }
        public virtual DbSet<Core_PartyTypes> Core_PartyTypes { get; set; }
        public virtual DbSet<Core_Providers> Core_Providers { get; set; }
        public virtual DbSet<Core_ServiceCatalog> Core_ServiceCatalog { get; set; }
        public virtual DbSet<Core_CosumerServices> Core_CosumerServices { get; set; }
    }
}
