//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2_FromScratch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Core_CnsServiceUnit> Core_CnsServiceUnit { get; set; }
        public virtual DbSet<Core_PartyConsumerInfo> Core_PartyConsumerInfo { get; set; }
        public virtual DbSet<Core_PartyMaster> Core_PartyMaster { get; set; }
        public virtual DbSet<Core_PartyProviderInfo> Core_PartyProviderInfo { get; set; }
        public virtual DbSet<Core_PartyService> Core_PartyService { get; set; }
        public virtual DbSet<Core_PrvServiceUnit> Core_PrvServiceUnit { get; set; }
    }
}
